### ISSUE TITLE
ng start with exit code 1

### ISSUE THREAD

**Issue by KlausEichinger** [CodeSequence/ngrx-workshop#2]
Hello,

after cloning the repo to my desktop I run `ng start`. It fails with exit code 1:

`86% hashingcrypto.js:97
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:97:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
    at /Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/Module.js:162:41)
    at NormalModule.updateHash (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/NormalModule.js:327:30)
    at modules.forEach.m (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/Chunk.js:253:16)
    at Compilation.createHash (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/Compilation.js:1121:10)
    at sealPart2 (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/Compilation.js:605:9)
    at next (/Users/klaus/dev/ngrx-workshop-master/node_modules/tapable/lib/Tapable.js:184:11)
    at Compilation.<anonymous> (/Users/klaus/dev/ngrx-workshop-master/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at next (/Users/klaus/dev/ngrx-workshop-master/node_modules/tapable/lib/Tapable.js:186:14)
    at ExtractTextPlugin.<anonymous> (/Users/klaus/dev/ngrx-workshop-master/node_modules/extract-text-webpack-plugin/index.js:305:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! workshop@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the workshop@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/klaus/.npm/_logs/2017-07-31T17_37_36_621Z-debug.log

Process finished with exit code 1 `

**Comment by librasean** [comment]
It's because `@angular/material` has changed to need a peer dependency of `@angular/cdk` 
So 
`npm install --save @angular/cdk`
Also I had to add
`import 'rxjs/add/operator/catch';`
To google-books.service.ts
And change the material theme to:
`@import "~@angular/material/prebuilt-themes/indigo-pink.css";`
in styles.css

I'll submit PR with the changes but all that being said you may just want to lock down the dependencies used currently on master for easy moving to follow the steps on the other branchs.
So change package.json
and remove the ^ from @angular/material and rxjs to use those specific version:
    `"rxjs": "5.1.0",`
    `"@angular/material": "2.0.0-beta.3",`
